version: '3.3'

services:
  app:
    image: 'antongongelev/football'
    ports:
      - "8787:8787"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/football_bot_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      #  Укажите желаемые настройки для бота ниже (нужны кавычки, если слов несколько):
      - DOMAIN_CHAT_ID=-100840047547
      - DOMAIN_BOT_NAME=PortugalFootballBot
      - DOMAIN_BOT_TOKEN=6055053880:AAG9kbnyelO2bRfVWpYLl5T3SE2CLhOZ_18
      - DOMAIN_FOOTBALL_DAY=Среда-20:00;Воскресенье-20:00
      - DOMAIN_FOOTBALL_CHECK_IN_BEFORE_HOURS=60
      - DOMAIN_FOOTBALL_CHECK_IN_HOUR=12
      - DOMAIN_FOOTBALL_SEND_TEAM_REPORT_BEFORE_HOURS=1
      - DOMAIN_FOOTBALL_IS_IGNORE_ADDITION=true
      - DOMAIN_FOOTBALL_IS_IGNORE_INTERROGATION=true

  db:
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=football_bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "PGPASSWORD=postgres pg_isready -h 127.0.0.1 -U postgres -d football_bot_db"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
