version: '3.3'

services:
  app:
    image: 'football'
    ports:
      - "8787:8787"
    depends_on:
      - db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/football_bot_db
      - SPRING_DATASOURCE_USERNAME=football_bot_user
      - SPRING_DATASOURCE_PASSWORD=football_bot_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      #  Укажите желаемые настройки для бота ниже (нужны кавычки, если слов несколько):

      - DOMAIN_CHAT_ID=-300581737
      - DOMAIN_BOT_NAME=GAZ_TEAM_BOT
      - DOMAIN_BOT_TOKEN=7395289491:AAELT6VYKVHsJJIWr1EzxLjOjUXfpTUZk9M

      - DOMAIN_FOOTBALL_DAY=Вторник-19:00, Суббота-10:00
      - DOMAIN_FOOTBALL_CHECK_IN_BEFORE_HOURS=48
      - DOMAIN_FOOTBALL_SEND_TEAM_REPORT_BEFORE_HOURS=1
      - DOMAIN_FOOTBALL_IS_IGNORE_ADDITION=false
      - DOMAIN_FOOTBALL_IS_IGNORE_INTERROGATION=false

  db:
    image: 'postgres'
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=football_bot_db
      - POSTGRES_USER=football_bot_user
      - POSTGRES_PASSWORD=football_bot_password
    healthcheck:
      test: "PGPASSWORD=football_bot_password pg_isready -h 127.0.0.1 -U football_bot_user -d football_bot_db"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
