domain:
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}
  chat:
    name: ${CHAT_NAME}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    pool-size: 5
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
