domain:
  bot:
    name:
    token:
  chat:
    name:
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_bot_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
