domain:
  bot:
    name: GongeliniTestBot
    token: 5095369262:AAH3X0MmvI0kMly9W83JqPeW28aqCdPiGGk
  chat:
    name: NewGroup
  football:
    day: Вторник_19:30;Пятница_04:00
    check-in-before-hours: 48
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_bot_db
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate