version: '3.6'

services:
  postgres:
    image: postgres:11.11-alpine
    container_name: footbalbot_postgres
    volumes:
      - pgsdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: none

volumes:
  pgsdata:
